- name: Update apt cache
  shell: apt update

- name: Install dependencies
  package:
    name:
      - docker.io
      - docker-compose={{ docker_compose_version }}

- name: enable service docker and ensure it is started
  service:
    name: docker
    enabled: yes
    state: started

- name: start and enable containerd daemon
  service:
    name: containerd
    state: started
    enabled: yes

- name: Add cron job to keep the server clean
  ansible.builtin.cron:
    name: "docker-clean"
    state: present
    special_time: "weekly"
    job: "/usr/bin/docker system prune -af --volumes"

- name: List Linux block devices
  ansible.builtin.shell:
    cmd: "lsblk -o PATH,SERIAL | grep {{ docker_extra_ebs_volume_id | replace('-', '') }} | cut -d' ' -f1"
  register: lsblk
  when: docker_extra_vol_mount

- name: Store EBS volume device name
  ansible.builtin.set_fact:
    ebs_volume_device_name: "{{ lsblk.stdout }}"
  when: docker_extra_vol_mount

- name: Create a ext4 filesystem for extra vol
  filesystem:
    fstype: ext4
    dev: "{{ ebs_volume_device_name }}"
  when: docker_extra_vol_mount

- name: Create a volume
  community.docker.docker_volume:
    name: "{{ docker_extra_volume_name }}"
    state: present
    driver_options:
      type: ext4
      device: "{{ ebs_volume_device_name }}"
  when: docker_extra_vol_mount
