netmaker_root_dir: /root/netmaker-compose
netmaker_image_version: 0.18.7
netclient_enrollment_keys: ["cntrlctr-ops"]
netmaker_join_tokens: []
netmaker_enrollment_key_list_file_location: /tmp/keylist.json
egress_gateway_cidr: 10.106.0.0/23
netmaker_api_host: api.netmaker.domain
netmaker_master_key: crazypassword
teardown: false
