argocd_version: "2.8.2"
argocd_lovely_plugin_version: "0.18.0"
repo_url: "https://localhost/repo.git"
repo_password: mypassword
repo_username: user
external_secrets_version: "0.9.0"
external_secrets_namespace: "external-secrets"
tenant_vault_token: token
tenant_vault_server_url: "https://tenantvault"
kubeconfig_location: "/root/.kube"
root_app_path: "infra/app-yamls"
netmaker_image_version: "0.18.7"
wireguard_node_port: "31821"
cluster_name: envname
kubeconfig_local_location: "/tmp"
kustomize_version: "3.2.3"
kubectl_version: "1.24.6"
coredns_version: "1.28.2"
coredns_max_scale: 10
install_nodelocaldns: false
